insert into tasks (title, description, due_date, status) values ('Contraband', 'Avoidant personality disorder', '2024-01-11 00:30:24', 'PENDING');
insert into tasks (title, description, due_date, status) values ('My House in Umbria', 'Spinal enthesopathy, thoracic region', '2023-12-17 14:14:56', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Day of the Falcon', 'Toxic effect of benzene, assault, sequela', '2024-01-30 08:44:20', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Money Money Money (L''aventure, c''est l''aventure)', 'Lattice corneal dystrophy', '2023-12-10 22:56:49', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Lights in the Dusk (Laitakaupungin valot)', 'Human immunodef virus disease comp preg, second trimester', '2023-07-29 00:51:51', 'PENDING');
insert into tasks (title, description, due_date, status) values ('My Bodyguard', 'Disorder of ligament, left ankle', '2024-03-01 03:51:44', 'PENDING');
insert into tasks (title, description, due_date, status) values ('I Will Buy You (Anata kaimasu)', 'Unsp physeal fx lower end of humerus, left arm, sequela', '2023-10-15 14:39:54', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Stella Street', 'Abrasion of right middle finger, sequela', '2023-04-20 07:36:42', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Reel Rock 8 ', 'Other hypertrophic osteoarthropathy, right ankle and foot', '2024-01-17 23:23:56', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Making ''Do the Right Thing''', 'Partial traum amp of two or more left lesser toes, sequela', '2023-12-29 18:29:27', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Tango', 'Displ seg fx shaft of unsp fibula, 7thF', '2024-01-26 08:52:00', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Water Horse: Legend of the Deep, The', 'Laceration w/o foreign body of right forearm, init encntr', '2023-12-08 05:24:12', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Matrix, The', 'Viral endocarditis', '2024-02-18 06:34:10', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Seaside (Bord de Mer)', 'Legal intervnt w unsp explosv, suspect injured, sequela', '2023-11-26 20:38:35', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Guest from the Future (Gostya iz buduschego)', 'Cerebral infarction, unspecified', '2024-02-28 08:27:47', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Can Go Through Skin (Kan door huid heen)', 'Displaced spiral fracture of shaft of unspecified tibia', '2023-10-26 16:30:20', 'PENDING');
insert into tasks (title, description, due_date, status) values ('License to Drive', 'Occlusion and stenosis of bilateral carotid arteries', '2023-06-17 11:31:52', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Vodka, Mr. Palmu (Vodkaa, komisario Palmu)', 'Poisoning by amphetamines, accidental (unintentional), subs', '2023-11-27 21:12:59', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Halloween', 'Inj oth flexor musc/fasc/tend at forarm lv, left arm, subs', '2023-12-20 12:34:20', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Breakfast Club, The', 'Open bite of unsp toe(s) with damage to nail, init encntr', '2023-12-31 20:44:26', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Mod Squad, The', 'Occupational exposure to vibration', '2023-10-04 22:32:37', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Batman and Robin', 'Cryptococcosis', '2024-02-15 21:51:57', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Penitentiary II', 'Unsp inj flexor musc/fasc/tend unsp fngr at forarm lv, subs', '2024-02-02 10:57:16', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Gate II: Trespassers, The', 'Epidural hemorrhage w LOC of 1-5 hrs 59 min, init', '2023-08-01 13:53:58', 'PENDING');
insert into tasks (title, description, due_date, status) values ('B. Monkey', 'Juvenile dermatopolymyositis with myopathy', '2023-09-23 04:10:20', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Behind the Screen', 'Oth disorders of bone development and growth, left ank/ft', '2023-12-22 07:48:49', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Crucified Lovers, The (Chikamatsu monogatari)', 'Osteonecrosis due to drugs, right humerus', '2023-06-07 08:38:28', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Average Italian', 'Crushing injury of unspecified thigh, sequela', '2023-07-08 00:44:39', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Lord of Tears', 'Nondisp fx of lateral condyle of r femr, 7thN', '2023-07-07 22:15:08', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Just an American Boy', 'Poisoning by anterior pituitary hormones, undetermined, init', '2024-01-16 04:15:13', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Suddenly (Tan de Repente)', 'Sltr-haris Type I physeal fx left metatarsal, sequela', '2023-06-08 08:35:33', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Savage Streets', 'External constriction of part of throat, sequela', '2023-09-03 14:52:28', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Feast of July', 'Corrosions of other and unspecified internal organs', '2023-06-03 16:10:37', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Fall Time', 'Other specified hypertrophy of vulva', '2024-01-18 07:22:08', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Europeans, The', 'Other superficial mycoses', '2023-05-03 13:59:16', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Few Good Men, A', 'Other specified injuries of left foot, sequela', '2023-05-22 16:48:55', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Starsuckers', 'Poisn by antiparkns drug/centr musc-tone depr, undet, sqla', '2023-05-06 13:22:06', 'PENDING');
insert into tasks (title, description, due_date, status) values ('About a Boy', 'Disp fx of med condyle of r femr, 7thQ', '2024-01-20 03:27:22', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Enemy Within, The (O ehthros mou)', 'Stress fracture, left humerus, subs for fx w routn heal', '2023-12-15 18:49:22', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Cut and Run (Inferno in diretta)', 'Acute bronchiolitis due to respiratory syncytial virus', '2023-06-15 20:07:50', 'PENDING');
insert into tasks (title, description, due_date, status) values ('The Improv: 50 Years Behind the Brick Wall', 'Osteonecrosis due to previous trauma, left tibia', '2023-04-20 08:02:49', 'PENDING');
insert into tasks (title, description, due_date, status) values ('White Countess, The', 'Unsp inj extensor musc/fasc/tend finger at wrs/hnd lv, init', '2023-12-16 15:07:55', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Runaway', 'Traumatic compartment syndrome of abdomen, subs encntr', '2023-07-09 08:41:12', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Great Expectations', 'Partial traum amp at level betw knee and ankle, r low leg', '2023-09-15 02:26:35', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Lush Life', 'Serous retinal detachment, left eye', '2023-09-22 19:45:05', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Cost of Living, The (Le coût de la vie)', 'Unsp fx shaft of l tibia, 7thE', '2023-10-24 00:47:18', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Miss Meadows', 'Scleritis with corneal involvement, unspecified eye', '2024-01-03 19:24:44', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Green Wave, The', 'Unsp injury of musc/fasc/tend at neck level, sequela', '2023-09-14 21:22:01', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Hellfighters', 'Nondisp unsp fx unsp great toe, subs for fx w malunion', '2023-11-26 02:46:09', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Shootist, The', 'Other specified injuries of unspecified elbow, sequela', '2024-03-13 15:18:27', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Second Jungle Book: Mowgli & Baloo, The', 'Poisoning by thrombolytic drug, intentional self-harm', '2023-07-14 19:00:36', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Mahogany', 'Poisoning by sulfonamides, assault, subsequent encounter', '2023-08-13 16:50:49', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Northeast', 'Infect/inflm reaction due to int fix of left fibula, subs', '2023-07-04 01:04:59', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Love Affair', 'Displ suprcndl fx w intrcndl extn low end unsp femr, 7thN', '2023-04-21 22:23:26', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Koti-ikävä', 'Traumatic cerebral edema w LOC of 1-5 hrs 59 min, init', '2023-10-04 18:24:36', 'PENDING');
insert into tasks (title, description, due_date, status) values ('I Am Maria (Jag är Maria)', 'Prsn brd/alit from bus inj in clsn w statnry object, init', '2024-03-21 06:52:27', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Mission: Impossible - Ghost Protocol', 'Toxic effect of 2-Propanol, assault, subsequent encounter', '2023-12-13 01:13:53', 'PENDING');
insert into tasks (title, description, due_date, status) values ('The Substitute 2: School''s Out', 'Bent bone of right ulna', '2023-10-03 20:21:42', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Silent Action', 'Toxic effect of manganese and its compounds, undetermined', '2023-08-19 11:17:48', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Householder, The (Gharbar)', 'Oth disorders of kidney and ureter, not elsewhere classified', '2023-04-29 06:26:28', 'PENDING');
insert into tasks (title, description, due_date, status) values ('TerrorStorm: A History of Government-Sponsored Terrorism', 'Ped w convey injured in clsn w 2/3-whl mv nontraf, sequela', '2024-01-28 00:05:13', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Julius Caesar', 'Complete lesion at C6 level of cervical spinal cord, sequela', '2023-08-26 23:05:31', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Dark Angel (I Come in Peace)', 'Sprain of interphalangeal joint of unsp finger, sequela', '2023-07-31 13:58:39', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Train', 'Disp fx of olecran pro w/o intartic extn r ulna, 7thR', '2023-05-30 18:28:38', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Pride and Prejudice', 'Unspecified fracture of shaft of ulna', '2024-02-10 13:40:49', 'PENDING');
insert into tasks (title, description, due_date, status) values ('George Washington', 'Traum hemor l cereb w LOC >24 hr w/o ret consc w surv, subs', '2023-08-09 23:30:04', 'PENDING');
insert into tasks (title, description, due_date, status) values ('The Princess Comes Across', 'Laceration without foreign body of scalp, initial encounter', '2023-08-12 06:30:19', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Schwestern', 'Dislocation of radiocarpal joint of unspecified wrist', '2023-05-01 11:37:01', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Dr. Akagi (Kanzo sensei)', 'Unspecified sprain of left thumb, subsequent encounter', '2024-03-05 07:21:05', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Lost in Yonkers', 'Maternal care for fetal problem, unsp, unsp trimester, unsp', '2023-11-28 07:32:56', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Right at Your Door', 'Sltr-haris Type I physeal fx lower end of left fibula', '2023-06-10 06:40:26', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Waist Deep', 'Oth rheumatoid arthritis w rheumatoid factor of right ank/ft', '2024-02-01 07:59:58', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Our Song', 'Nondisp Zone I fracture of sacrum, subs for fx w delay heal', '2024-01-28 15:14:07', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Madame Sin', 'Other fracture of left patella, sequela', '2023-12-12 00:12:22', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Eye of Vichy, The (Oeil de Vichy, L'')', 'Inj femoral vein at hip and thigh level, left leg, subs', '2023-10-23 07:45:15', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Vampyros Lesbos (Vampiras, Las)', 'Nondisp fx of low epiphy (separation) of r femr, 7thE', '2024-03-17 20:23:45', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Tony Takitani', 'Chronic myelomonocytic leukemia, in relapse', '2023-07-20 09:23:41', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Cockpit', 'Cerebral infarction due to embolism of vertebral artery', '2023-06-14 05:45:36', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Blue Light, The (Blaue Licht, Das)', 'Complete traum amp of unsp hip and thigh, level unsp, init', '2024-01-04 21:21:21', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Poseidon Adventure, The ', 'Breakdown (mechanical) of intrauterine contraceptive device', '2024-01-08 15:59:55', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Hawaiians, The', 'Complete traumatic amputation of right great toe, subs', '2023-04-13 06:58:41', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Amen.', 'Displ transverse fx shaft of l fibula, 7thB', '2023-11-02 09:58:27', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Our Relations', 'Puncture wound with foreign body of unsp hand, subs encntr', '2023-04-25 21:21:24', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Talking Picture, A (Um Filme Falado)', 'Chondromalacia patellae, left knee', '2024-04-06 15:53:20', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Rage of Honor', 'Follicular lymphoma, unsp, extranodal and solid organ sites', '2023-10-19 14:11:44', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Ice Castles', 'Nondisp fx of hook process of hamate bone, right wrist', '2023-04-19 20:21:40', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Big Game', 'Displ oblique fx shaft of unsp ulna, 7thR', '2024-03-16 21:42:26', 'PENDING');
insert into tasks (title, description, due_date, status) values ('I Love You, Beth Cooper', 'Burns involving 10-19% of body surface', '2023-09-07 21:57:37', 'PENDING');
insert into tasks (title, description, due_date, status) values ('LEGO DC Comics Super Heroes: Justice League vs. Bizarro League', 'Athscl nonbiol bypass of the right leg w ulcer of unsp site', '2024-04-05 21:25:13', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Leslie, My Name is Evil (Manson, My Name is Evil)', 'Local-rel (focal) symptc epi w simple partial seiz, ntrct', '2023-09-05 01:52:46', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Wholly Moses', 'Nondisp fx of lateral epicondyl of l humer, 7thD', '2024-02-24 02:09:52', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Scooby-Doo', 'Blister (nonthermal) of right thumb, subsequent encounter', '2023-09-08 12:52:07', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Sixtynine', 'Occ of rail trn/veh inj due to object fall onto train, init', '2024-02-23 02:21:43', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Offence, The', 'Other derangements of patella, left knee', '2024-01-07 03:57:27', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Obvious Child', 'Vitamin D deficiency', '2023-08-01 09:58:56', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Jönssonligans största kupp', 'Short Achilles tendon (acquired), right ankle', '2023-06-20 12:26:56', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Craigslist Joe', 'Unspecified disease of inner ear, bilateral', '2024-03-07 08:54:46', 'PENDING');
insert into tasks (title, description, due_date, status) values ('The Arrival of Wang', 'Other assault by crashing of motor vehicle, init encntr', '2023-08-14 00:11:09', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Saint John of Las Vegas', 'Nondisp fx of capitate bone, r wrist, subs for fx w nonunion', '2023-05-24 03:38:29', 'PENDING');
insert into tasks (title, description, due_date, status) values ('Battlefield Earth', 'Puncture wound w/o foreign body of right upper arm, subs', '2024-02-24 08:44:34', 'PENDING');